### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by chnl** [mallahyari/RealtimeSTT-TTS#1]
RealtimeSTT-TTS\backend\app\main.py", line 5, in <module>
    from app.api.api_v1.routers.styletts import audio_router
ModuleNotFoundError: No module named 'app'

**Comment by mallahyari** [comment]
It's because your python is not in the path. what you need to do to fix the problem is go inside the "backend" folder via terminal and run this command:

export PYTHONPATH=$PWD

Then run python app/main.py

It should fix the problem. Let me know if you still have a issue.
